# Site Settings
baseurl: ""
url : "https://malladisiddu.github.io"

# Blog Settings
theme_settings :
  title : Siddartha Malladi
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Siddartha Malaldi
    description : 3rd year ECE Undergrad at <a href=\"https://amrita.edu\">Amrita University</a> Bangalore Campus, Cybersecurity enthusisat, CTFs with <a href=\"https://ctftime.org/team/72702\">c0d3_h4cki05_</a>, Focuses mainly on Crypto challenges.
    experience :
      - start : 2019-01-08
        end : present
        experience : c0d3_h4cki05_, Cryptanalyst
      - start : 2019-07-26
        end : present
        experience : IEEE ComSoc (student club), Joint Secretary
      - start : 2018-09-14
        end : 2018-12-20
        experience : Internshala, Campus Ambassdor        
    skills : 
      - skill : Python
        value : 75  # Percent value
      - skill : C
        value : 70  # Percent value
      - skill : Cryptanalysis
        value : 70  # Percent value                       
        
  # Icons
  icons :
    email:  malladisiddu@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/siddartha-malladi/ # Full URL 
    github: malladisiddu
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: st0ic3r
    youtube:
    facebook:
    instagram: st0ic3r

  # Disqus
  disqus_shortname : siddarthamalladi

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
